#+title: ANX-Docgen Design Notes
#+author: Rich Loveland
#+email: rloveland@appnexus.com

* Overview

  ANX-Docgen is an Emacs Lisp package that is designed to
  automatically create formatted documentation tables from the JSON
  returned by various AppNexus API services' `/meta' calls.

* Data Format

  You are given an array of JSON objects, which is converted into an
  array of Lisp association lists .

  For each association list (or /alist/), the following information is
  available:

  | Field    | Type             | Sort by? | Filter by? |
  |----------+------------------+----------+------------|
  | snapshot | array of objects | false    | false      |
  |          |                  |          |            |

  If the alist's /type/ value is ``array of objects'', the =fields=
  key will also be available, which is itself an array of objects.

* Implementation

  As a first cut, we will implement a ``two-pass'' solution. We
  iterate over the array of objects, printing the /name/, /type/,
  /sort_by/ and /filter_by/ values into a tabular format.
  
  If the /type/ is ``array of objects'', there should be a /fields/
  key. If this key exists, we will cons the name of the current
  object onto the array of objects in /fields/, and then push /fields/
  onto a stack.

  After the first pass, when we've printed out the initial table, we
  will then pop items off of the stack one by one, printing them out
  in a tabular format as well.
