#+title: Notes on ANX-Docgen
#+author: Rich Loveland
#+email: loveland.richard@gmail.com

* A New Intermediate Representation is Needed

  Instead of focusing on Confluence's current formatting preferences
  as our (moving) target, we propose to get our documentation tables
  into Lisp as an intermediate representation. From there we can
  transform it to whatever we need. Below are some proposed data
  representations for working with both regular APIs and reports.

* The Proposed New Document Structure

  The document below is represented as an alist, which has some nice
  properties. For example, we can query any section of the document
  programmatically and read or modify its contents.

** Standard APIs

  | JSON Fields (Parent Table)                |
  |-------------------------------------------|
  | More JSON Fields (Child Tables)           |
  |-------------------------------------------|
  | Even more JSON Fields (Grandchild Tables) |

   #+begin_src emacs-lisp
     ((parent ((title (text "JSON Fields")) 
               (header ("Name" "Type" "Sort by?" "Filter by?" "Description" "Default" "Required on")) 
               (items ((name . "inventory_attributes") 
                       (type . "array of objects") 
                       (sort_by . "No") 
                       (filter_by . "No") 
                       (description . "") 
                       (default . "") 
                       (required_on . "")) 
                      ((name . "supported_media_types") 
                       (type . "array of objects") 
                       (sort_by . "No") 
                       (filter_by . "No") 
                       (description . "") 
                       (default . "") 
                       (required_on . "")) 
                      ;; etc.
                      )))
      (children (((title (text "Inventory_Attributes")) 
                  (header ("Name" "Type" "Sort by?" "Filter by?" "Description" "Default" "Required on")) 
                  (items ((name . "id") 
                          (type . "int") 
                          (sort_by . "No") 
                          (filter_by . "No") 
                          (description . "") 
                          (default . "") 
                          (required_on . "")) 
                         ((name . "name") 
                          (type . "string") 
                          (sort_by . "No") 
                          (filter_by . "No") 
                          (description . "") 
                          (default . "") 
                          (required_on . "")))) 
                 ((title (text "Supported_Media_Types")) 
                  (header ("Name" "Type" "Sort by?" "Filter by?" "Description" "Default" "Required on")) 
                  (items ((name . "id") 
                          (type . "int") 
                          (sort_by . "No") 
                          (filter_by . "No") 
                          (description . "") 
                          (default . "") 
                          (required_on . "")) 
                         ((name . "name") 
                          (type . "string") 
                          (sort_by . "No") 
                          (filter_by . "No") 
                          (description . "") 
                          (default . "") 
                          (required_on . ""))))
                 ;; etc.
                 )))
     
   #+end_src
  
** The Report Service

  | Dimensions |
  |------------|
  | Metrics    |

   #+begin_src emacs-lisp
     '((dimensions
       (title
        (text "Dimensions"))
       (header
        ("Column" "Type" "Group?" "Filter?" "Description"))
       (items ((column "advertiser") 
               (type "string")
               (filter_by "Yes")
               (description "The name and ID of the advertiser"))
              ((column "publisher") 
               (type "string")
               (group_by "Yes")
               (filter_by "Yes")
               (description "The name and ID of the publisher"))))
       (metrics
        (title
         (text "Metrics"))
        (header
         ("Column" "Type" "Formula" "Description"))
        (items ((column "imps")
                (type "int")
                (formula "imps")
                (description "The number of impressions"))
               ((column "clicks")
                (type "int")
                (formula "clicks")
                (description "The number of clicks")))))
     
   #+end_src

* How to Print It

** Standard APIs

   At the outermost level we have a `parent' and its `children'. We
   begin with the parent.

   The parent is an alist that has only one title, one set of columns,
   and a list of rows. It should be a simple matter to print them each
   in order.
   
* Things To Do

** TODO Figure out how to slurp field definition info

   This won't be that easy in cases where the info spans multiple lines.

** TODO Modify anx-docgen.el to output a Lispy representation

   - [ ] Report APIs
   - [X] Regular APIs

** TODO Look into esxml

   Rather than reinvent the wheel with your own format, research
   whether output from esxml will suffice.

** DONE Get everything under the 80-char limit!

** DONE Rewrite Lisp representation for standard reports as an alist

   See [[Report Services]].
