#+title: Notes on ANX-Docgen
#+author: Rich Loveland
#+email: loveland.richard@gmail.com

* A New Intermediate Representation is Needed

  Instead of focusing on Confluence's current formatting preferences
  as our (moving) target, we propose to get our documentation tables
  into Lisp as an intermediate representation. From there we can
  transform it to whatever we need. Below are some proposed data
  representations for working with both regular APIs and reports.

* The Proposed New Document Structure

  The document below is represented as an alist, which has some nice
  properties. For example, we can query any section of the document
  programmatically and read or modify its contents.

** Standard Services

  | JSON Fields (Parent Table)                |
  |-------------------------------------------|
  | More JSON Fields (Child Tables)           |
  |-------------------------------------------|
  | Even more JSON Fields (Grandchild Tables) |

   #+begin_src emacs-lisp
     '((json-fields
        (title
         (text "JSON Fields"))
        (header
         ("Field" "Type" "Sort by?" "Filter by?" "Description" "Default" "Required on"))
        (items
         (advertiser
          (field "advertiser") 
          (type "string")
          (sort_by "Yes")
          (filter_by "Yes")
          (description "The name and ID of the advertiser")
          (default "")
          (required_on ""))
         (publisher
          (field "publisher") 
          (type "string")
          (sort_by "Yes")
          (filter_by "Yes")
          (description "The name and ID of the publisher")
          (default "")
          (required_on ""))))
       (contract
        (title
         (text "Contract"))
        (header
         ("Field" "Type" "Sort by?" "Filter by?" "Description" "Default" "Required on"))
        (items
         (id
          (field "id")
          (type "int")
          (sort_by "Yes")
          (filter_by "Yes")
          (description "")
          (default "")
          (required_on ""))
         (status
          (field "status")
          (type "string")
          (sort_by "Yes")
          (filter_by "Yes")
          (description "")
          (default "")
          (required_on "")))))
   #+end_src
  
** Report Services

  | Dimensions |
  |------------|
  | Metrics    |

   #+begin_src emacs-lisp
     '((dimensions
       (title
        (text "Dimensions"))
       (header
        ("Column" "Type" "Group?" "Filter?" "Description"))
       (items
        (advertiser
         (column "advertiser") 
         (type "string")
         (group_by "Yes")
         (filter_by "Yes")
         (description "The name and ID of the advertiser"))
        (publisher
         (column "publisher") 
         (type "string")
         (group_by "Yes")
         (filter_by "Yes")
         (description "The name and ID of the publisher"))))
       (metrics
        (title
         (text "Metrics"))
        (header
         ("Column" "Type" "Formula" "Description"))
        (items
         (imps
          (column "imps")
          (type "int")
          (formula "imps")
          (description "The number of impressions"))
         (clicks
          (column "clicks")
          (type "int")
          (formula "clicks")
          (description "The number of clicks")))))
     
   #+end_src

* Things To Do

** TODO Modify anx-docgen.el to output Lisp

** TODO Look into esxml

   Rather than reinvent the wheel with your own format, research
   whether output from esxml will suffice.

** DONE Rewrite intermediate Lisp representation for standard reports as an alist

   See [[Report Services]].
