#+title: ANX-Docgen TODO
#+author: Rich Loveland
#+email: rloveland@appnexus.com

** TODO Write a proper README

   Should have:

   - [ ] Prerequisites
   - [ ] Install
   - [ ] Usage

** TODO Determine a proper author email address for this repo

   And then update to it.

** TODO Consider switching to GPL as you did for `anx-api`

** TODO Figure out how to slurp field definition info from existing documentation

   This won't be that easy in cases where the info spans multiple
   lines. Now that we're upgrading Confluence, it could get easier,
   since we'll only have access to a crap XML-ish format (which at
   least has a parser).

** TODO Modify anx-docgen.el to output a Lispy representation

   - [ ] Report APIs
   - [X] Regular APIs

** TODO Look into using esxml

   Rather than reinvent the wheel with your own format, research
   whether input/output to/from esxml will suffice.

** DONE Get everything under the 80-char limit!

** DONE Rewrite Lisp representation for standard reports as an alist

   See [[Report Services]].
